name: Build gallformers project

on: [push, pull_request]

  # Run tests for any PRs.
  #pull_request:

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Build gallformers image
        run: make build
